DBT_Cloud_Project:
  outputs:
    dev:
      type: databricks
      catalog: dev_env
      host: dbc-10b9cc1d-f2fd.cloud.databricks.com
      http_path: /sql/1.0/warehouses/e3a99c2381181670
      schema: default
      threads: 1
      token: ""

  target: dev
